---

- name: Include cluster configuration
  ansible.builtin.include_tasks:
    file: configure_cluster.yml
    apply:
      tags:
        - pacemaker
  when:
    - pacemaker_corosync_group in groups
  tags:
    - pacemaker

- name: Include remote resource configuration
  ansible.builtin.include_tasks:
    file: configure_remote_resource.yml
    apply:
      tags:
        - pacemaker-remote
  when:
    - pacemaker_remote_register_resource | bool
  tags:
    - pacemaker-remote
