---

- name: Importing variables check
  ansible.builtin.import_tasks: check_vars.yml
  tags:
    - pacemaker
    - check

- name: Prepare system for cluster deployment
  ansible.builtin.import_tasks:
    file: pre_install.yml
  tags:
    - pacemaker

- name: Importing pacemaker tasks
  ansible.builtin.import_tasks: install.yml
  tags:
    - pacemaker
    - pacemaker-remote

- name: Ensure that pacemaker-remote nodes are not part of cluster
  ansible.builtin.include_tasks:
    file: cleanup_remote_node.yml
    apply:
      tags:
        - pacemaker-remote
  when:
    - _pacemaker_remote_group_exists | bool
    - inventory_hostname in groups.get(pacemaker_remote_group, [])
    - inventory_hostname not in groups.get(pacemaker_corosync_group, [])
  tags:
    - pacemaker-remote
