---

- name: Importing variables check
  ansible.builtin.import_tasks: check_vars.yml
  tags:
    - pacemaker
    - check

- name: Importing pacemaker tasks
  ansible.builtin.import_tasks: pacemaker.yml
  tags:
    - pacemaker
