---

- name: Ensure all pre-requisites are installed
  ansible.builtin.package:
    name: gnupg2
    state: present

- name: Configure DNF
  when:
    - ansible_facts['os_family'] | lower == 'redhat'
  block:
    - name: Ensure config-manager is present for dnf
      ansible.builtin.package:
        name: dnf-plugins-core
        state: present
      when:
        - ansible_facts['distribution_major_version'] is version('8', '>=')

    - name: Enable HighAvailability repository
      ansible.builtin.command: "dnf config-manager --enable {{ _centos_ha_repo_name[ansible_facts['distribution_major_version']] }}"
      changed_when: false
