---

- name: Ensure all pre-requisites are installed
  ansible.builtin.package:
    name: gnupg2
    state: present

- name: Configure DNF
  when:
    - ansible_facts['os_family'] | lower == 'redhat'
  block:
    - name: Ensure config-manager is present for dnf
      ansible.builtin.package:
        name: dnf-plugins-core
        state: present
      when:
        - ansible_facts['distribution_major_version'] is version('8', '>=')

    - name: Enable HighAvailability repository
      ansible.builtin.command: "dnf config-manager --enable {{ _centos_ha_repo_name[ansible_facts['distribution_major_version']] }}"
      changed_when: false

- name: Install EPEL repo for haveged
  when:
    - pacemaker_corosync_haveged_enabled | bool
    - ansible_facts['os_family'] | lower == 'redhat'
  block:
    - name: Download EPEL gpg keys
      ansible.builtin.get_url:
        url: "{{ pacemaker_corosync_centos_epel_key }}"
        dest: /etc/pki/rpm-gpg
        mode: "0644"
      register: _get_yum_keys
      until: _get_yum_keys is success
      retries: 5
      delay: 2

    - name: Install EPEL gpg keys
      ansible.builtin.rpm_key:
        key: "/etc/pki/rpm-gpg/{{ pacemaker_corosync_centos_epel_key.split('/')[-1] }}"
        state: present

    - name: Install the EPEL repository
      ansible.builtin.yum_repository:
        name: epel-haveged
        baseurl: >-
          {{
            pacemaker_corosync_centos_epel_mirror ~ '/' ~ ansible_facts['distribution_major_version'] ~ (
              ansible_facts['distribution_major_version'] is version('8', '>=')) | ternary('/Everything/', '/') ~ ansible_facts['architecture']
          }}
        description: "Extra Packages for Enterprise Linux {{ ansible_facts['distribution_major_version'] }} - $basearch"
        gpgcheck: true
        enabled: true
        state: present
        includepkgs: "haveged"
      register: install_epel_repo
      until: install_epel_repo is success
      retries: 5
      delay: 2
