---
- name: Restart corosync
  ansible.builtin.service:
    name: corosync
    state: restarted
    enabled: true

- name: Restart pacemaker
  ansible.builtin.service:
    name: pacemaker
    state: restarted
    enabled: true
  when:
    - inventory_hostname in groups[pacemaker_corosync_group]
