---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: pacemaker
    image: "${docker_user:-quay.io/gotmax23}/${docker_image_tag:-ubuntu-systemd:noble}"
    command: ""
    pre_build_image: true
    groups:
      - corosync
    privileged: true
    networks:
      - name: bridge
      - name: pacemaker
    docker_networks:
      - name: pacemaker
        ipam_config:
          - subnet: 192.168.33.0/24

provisioner:
  name: ansible
  options:
    v: true
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../tests/test.yml
  config_options:
    defaults:
      inject_facts_as_vars: false

scenario:
  name: default
