---
- name: Prepare molecule instance
  hosts: all
  tasks:
    - name: Apt update and install rsync, ping, iproute
      ansible.builtin.apt:
        update_cache: true
        name:
          - rsync
          - inetutils-ping
          - iproute2
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Yum install iproute to fix undefined ansible_default_ipv4.address
      ansible.builtin.package:
        name: iproute
        state: present
      when:
        - ansible_facts['distribution'] == "CentOS"

    - name: Re-collect network facts required after installation iproute
      ansible.builtin.setup:
        gather_subset: network

    - name: Show ansible_interfaces
      ansible.builtin.debug:
        var: ansible_facts['interfaces']
